package se.lexicon.group_Reine.data;


import se.lexicon.group_Reine.data.database.MySqlConnection;
import se.lexicon.group_Reine.model.Person;
import se.lexicon.group_Reine.model.Todo;

import java.sql.*;
import java.util.ArrayList;
import java.util.Collection;

public class TodoItemsImpl implements TodoItems {


    /*Add a todo_item to database. ID gets generated by database and added to object
     * */
    @Override
    public Todo create(Todo todo) {
        String query = "insert into todo_item (title, description, deadline, done, assignee_id) " +
                "values (?,?,?,?,?)";
        int retrievedId;
        try (
                PreparedStatement preparedStatement =
                        MySqlConnection.getConnection().prepareStatement(query, Statement.RETURN_GENERATED_KEYS)
        ) {
            preparedStatement.setString(1, todo.getTitle());
            preparedStatement.setString(2, todo.getDescription());
            preparedStatement.setDate(3, todo.getDeadlineToMySqlFormat());
            preparedStatement.setBoolean(4, todo.isDone());
            preparedStatement.setInt(5, todo.getAssigneeId());
            int rowsAffected = preparedStatement.executeUpdate();
            if (rowsAffected == 1) {
                ResultSet resultSet = preparedStatement.getGeneratedKeys();
                if (resultSet.next()) {
                    retrievedId = resultSet.getInt(1);
                    todo.setTodoId(retrievedId);
                }
            } else {
                System.out.println("No todo ID retrieved from database");
            }
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        return todo;
    }

    /*Find all todo_item information from database
     * */
    @Override
    public Collection<Todo> findAll() {
        String query = "select * from todo_item";
        Collection<Todo> todoCollection = new ArrayList<>();
        try (
                Statement statement = MySqlConnection.getConnection().createStatement()
        ) {
            ResultSet resultSet = statement.executeQuery(query);
            while (resultSet.next()) {
                todoCollection.add(new Todo(
                        resultSet.getInt(1),
                        resultSet.getString(2),
                        resultSet.getString(3),
                        resultSet.getDate(4),
                        resultSet.getBoolean(5),
                        resultSet.getInt(6)
                ));
            }
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        return todoCollection;
    }

    /*Find todo_item information by id from database
     * */
    @Override
    public Todo findById(int id) {
        String query = "select * from todo_item where todo_id = ?";
        Todo todo = new Todo();
        try (
                PreparedStatement preparedStatement =
                        MySqlConnection.getConnection().prepareStatement(query)
        ) {
            preparedStatement.setInt(1, id);
            ResultSet resultSet = preparedStatement.executeQuery();
            if (resultSet.next()) {
                todo.setTodoId(resultSet.getInt(1));
                todo.setTitle(resultSet.getString(2));
                todo.setDescription(resultSet.getString(3));
                todo.setDeadlineFromMySqlFormat(resultSet.getDate(4));
                todo.setDone(resultSet.getBoolean(5));
                todo.setAssigneeId(resultSet.getInt(6));
            }
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        return todo;
    }

    /*Find todo_item information by done status from database
     * */
    @Override
    public Collection<Todo> findByDoneStatus(boolean done) {
        String query = "select * from todo_item where done = ?";
        Collection<Todo> todoCollection = new ArrayList<>();
        try (
                PreparedStatement preparedStatement =
                        MySqlConnection.getConnection().prepareStatement(query)
        ) {
            preparedStatement.setBoolean(1, done);
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                todoCollection.add(new Todo(
                        resultSet.getInt(1),
                        resultSet.getString(2),
                        resultSet.getString(3),
                        resultSet.getDate(4),
                        resultSet.getBoolean(5),
                        resultSet.getInt(6)
                ));
            }
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        return todoCollection;
    }

    /*Find todo_item information by assignee ID from database
     * */
    @Override
    public Collection<Todo> findByAssignee(int assigneeId) {
        String query = "select * from todo_item where assignee_id = ?";
        Collection<Todo> todoCollection = new ArrayList<>();
        try (
                PreparedStatement preparedStatement =
                        MySqlConnection.getConnection().prepareStatement(query)
        ) {
            preparedStatement.setInt(1, assigneeId);
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                todoCollection.add(new Todo(
                        resultSet.getInt(1),
                        resultSet.getString(2),
                        resultSet.getString(3),
                        resultSet.getDate(4),
                        resultSet.getBoolean(5),
                        resultSet.getInt(6)
                ));
            }
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        return todoCollection;
    }

    /*Find todo_item information by assignee person from database
     * */
    @Override
    public Collection<Todo> findByAssignee(Person assignee) {
        String query = "select * from todo_item where assignee_id = ?";
        Collection<Todo> todoCollection = new ArrayList<>();
        try (
                PreparedStatement preparedStatement =
                        MySqlConnection.getConnection().prepareStatement(query)
        ) {
            preparedStatement.setInt(1, assignee.getPersonID());
            ResultSet resultSet = preparedStatement.executeQuery();
            while (resultSet.next()) {
                todoCollection.add(new Todo(
                        resultSet.getInt(1),
                        resultSet.getString(2),
                        resultSet.getString(3),
                        resultSet.getDate(4),
                        resultSet.getBoolean(5),
                        resultSet.getInt(6)
                ));
            }
        } catch (SQLException throwables) {
            throwables.printStackTrace();
        }
        return todoCollection;
    }

    @Override
    public Collection<Todo> findByUnassignedTodoItems() {
        return null;
    }

    @Override
    public Todo updateTodo(Todo todo) {
        return null;
    }

    @Override
    public boolean deleteById(int id) {
        return false;
    }
}
